### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by TheBinaryGuy** [TheBinaryGuy/next-ts-starter#1]
Update README with appropriate text.

**Comment by aditya28sarin** [comment]
Can you assign this issue to me?

**Comment by TheBinaryGuy** [comment]
Done, sorry I was a little busy on some work stuff. Thanks for contributing!

**Comment by TheBinaryGuy** [comment]
Hey, @aditya28sarin you still want this issue?

**Comment by TheBinaryGuy** [comment]
Hey, I'm gonna go ahead and close the issue, thanks for chiming in!
